<?php    
$arrayDistrict = array(		
	array("id" => 20,  "ti" => "Quận Ba Đình"),
	array("id" => 21,  "ti" => "Quận Cầu Giấy"),
	array("id" => 22,  "ti" => "Quận Đống Đa"),
	array("id" => 23,  "ti" => "Quận Hà Đông"),
	array("id" => 24,  "ti" => "Quận Hai Bà Trưng"),
	array("id" => 25,  "ti" => "Quận Hoàn Kiếm"),
	array("id" => 26,  "ti" => "Quận Hoàng Mai"),
	array("id" => 27,  "ti" => "Quận Long Biên"),
	array("id" => 28,  "ti" => "Quận Tây Hồ"),
	array("id" => 29,  "ti" => "Quận Thanh Xuân"),
	array("id" => 674,  "ti" => "Ba Vì"),
	array("id" => 675,  "ti" => "Chương Mỹ"),
	array("id" => 676,  "ti" => "Đan Phượng"),
	array("id" => 677,  "ti" => "Đông Anh"),
	array("id" => 678,  "ti" => "Gia Lâm"),
	array("id" => 679,  "ti" => "Hoài Đức"),
	array("id" => 680,  "ti" => "Mê Linh"),
	array("id" => 681,  "ti" => "Mỹ Đức"),
	array("id" => 682,  "ti" => "Phú Xuyên"),
	array("id" => 683,  "ti" => "Phúc Thọ"),
	array("id" => 684,  "ti" => "Quốc Oai"),
	array("id" => 685,  "ti" => "Sóc Sơn"),
	array("id" => 686,  "ti" => "Thạch Thất"),
	array("id" => 687,  "ti" => "Thanh Oai"),
	array("id" => 688,  "ti" => "Thanh Trì"),
	array("id" => 689,  "ti" => "Thường Tín"),
	array("id" => 690,  "ti" => "Từ Liêm"),
	array("id" => 691,  "ti" => "Ứng Hòa"),
	array("id" => 692,  "ti" => "Thị xã Sơn Tây"),
);