<?php 
$arrayDistrict = array(
	array("id"=>760,"ti"=>	"Quận 1"),
	array("id"=>761,"ti"=>	"Quận 12"),
	array("id"=>762,"ti"=>	"Quận Thủ Đức"),
	array("id"=>763,"ti"=>	"Quận 9"),
	array("id"=>764,"ti"=>	"Quận Gò Vấp"),
	array("id"=>765,"ti"=>	"Quận Bình Thạnh"),
	array("id"=>766,"ti"=>	"Quận Tân Bình"),
	array("id"=>767,"ti"=>	"Quận Tân Phú"),
	array("id"=>768,"ti"=>	"Quận Phú Nhuận"),
	array("id"=>769,"ti"=>	"Quận 2"),
	array("id"=>770,"ti"=>	"Quận 3"),
	array("id"=>771,"ti"=>	"Quận 10"),
	array("id"=>772,"ti"=>	"Quận 11"),
	array("id"=>773,"ti"=>	"Quận 4"),
	array("id"=>774,"ti"=>	"Quận 5"),
	array("id"=>775,"ti"=>	"Quận 6"),
	array("id"=>776,"ti"=>	"Quận 8"),
	array("id"=>777,"ti"=>	"Quận Bình Tân"),
	array("id"=>778,"ti"=>	"Quận 7"),
	array("id"=>783,"ti"=>	"Huyện Củ Chi"),
	array("id"=>784,"ti"=>	"Huyện Hóc Môn"),
	array("id"=>785,"ti"=>	"Huyện Bình Chánh"),
	array("id"=>786,"ti"=>	"Huyện Nhà Bè"),
	array("id"=>787,"ti"=>	"Huyện Cần Giờ"),
);
