<?php 
$cityArray = array(
	array("id" => 1 , "ti" => "Bangkok"),
	array("id" => 2 , "ti" => "Nonthaburi"),
	array("id" => 3 , "ti" => "akhon Ratchasimaima"),
	array("id" => 4 , "ti" => "hiang Mai"),
	array("id" => 5 , "ti" => "at Yai"),
	array("id" => 6 , "ti" => "don Than"),
	array("id" => 7 , "ti" => "ak Kret"),
	array("id" => 8 , "ti" => "hon Kaen"),
	array("id" => 9 , "ti" => "haophraya Surasakri"),
	array("id" =>10, "ti" => "Ubon Ratchathaniani"),
	array("id" =>11, "ti" => "Nakhon Si Thammarathammarat"),
	array("id" =>12, "ti" => "Nakhon Sawan"),
	array("id" =>13, "ti" => "Nakhon Pathom"),
	array("id" =>14, "ti" => "Phitsanulok"),
	array("id" =>15, "ti" => "Pattaya"),
	array("id" =>16, "ti" => "Songkhla"),
	array("id" =>17, "ti" => "Surat Thani"),
	array("id" =>18, "ti" => "Rangsit"),
	array("id" =>19, "ti" => "Yala, ThailandY"),
	array("id" =>20, "ti" => "Phuket"),
	array("id" =>21, "ti" => "Samut Prakan"),
	array("id" =>22, "ti" => "Lampang"),
	array("id" =>23, "ti" => "Laem Chabang"),
	array("id" =>24, "ti" => "Chiang Rai"),
	array("id" =>25, "ti" => "Trang"),
	array("id" =>26, "ti" => "Phra Nakhon Si Ayutthaya"),
	array("id" =>27, "ti" => "Ko Samui"),
	array("id" =>28, "ti" => "Samut Sakhon"),
	array("id" =>29, "ti" => "Rayong"),
	array("id" =>30, "ti" => "Mae Sot"),
	array("id" =>31, "ti" => "Om Noi"),
	array("id" =>32, "ti" => "Sakon Nakhon"),
);	