<?php 
$cityArray = array(
   array( "id" => 30, "ti" => 'Hồ Chí Minh'),
   array( "id" => 23, "ti" => 'Hà Nội'),
   array( "id" => 15, "ti" => 'Đà Nẵng'),
   array( "id" => 13, "ti" => 'Cần Thơ'),
   array( "id" => 27, "ti" => 'Hải Phòng'),
   array( "id" => 1 , "ti"=> 'An Giang'),
   array( "id" => 2 , "ti"=> 'Bà Rịa Vũng Tàu'),
   array( "id" => 3 , "ti"=> 'Bạc Liêu'),
   array( "id" => 4 , "ti"=> 'Bắc Kạn'),
   array( "id" => 5 , "ti"=> 'Bắc Ninh'),
   array( "id" => 6 , "ti"=> 'Bắc Giang'),
   array( "id" => 7 , "ti"=> 'Bến Tre'),
   array( "id" => 8 , "ti"=> 'Bình Định'),
   array( "id" => 9 , "ti"=> 'Bình Phước'),
   array( "id" => 10, "ti" => 'Bình Thuận'),
   array( "id" => 11, "ti" => 'Bình Dương'),
   array( "id" => 12, "ti" => 'Cà Mau'),
   array( "id" => 14, "ti" => 'Cao Bằng'),
   array( "id" => 16, "ti" => 'Đắk Lắk'),
   array( "id" => 17, "ti" => 'Đắk Nông'),
   array( "id" => 18, "ti" => 'Điện Biên'),
   array( "id" => 19, "ti" => 'Đồng Nai'),
   array( "id" => 20, "ti" => 'Đồng Tháp'),
   array( "id" => 21, "ti" => 'Gia Lai'),
   array( "id" => 22, "ti" => 'Hà Giang'),
   array( "id" => 24, "ti" => 'Hà Nam'),
   array( "id" => 25, "ti" => 'Hà Tĩnh'),
   array( "id" => 26, "ti" => 'Hải Dương'),
   array( "id" => 28, "ti" => 'Hậu Giang'),
   array( "id" => 29, "ti" => 'Hoà Bình'),
   array( "id" => 31, "ti" => 'Hưng Yên'),
   array( "id" => 32, "ti" => 'Khánh Hoà'),
   array( "id" => 33, "ti" => 'Kiên Giang'),
   array( "id" => 34, "ti" => 'Kon Tum'),
   array( "id" => 35, "ti" => 'Lai Châu'),
   array( "id" => 36, "ti" => 'Lâm Đồng'),
   array( "id" => 37, "ti" => 'Lạng Sơn'),
   array( "id" => 38, "ti" => 'Lào Cai'),
   array( "id" => 39, "ti" => 'Long An'),
   array( "id" => 40, "ti" => 'Nam Định'),
   array( "id" => 41, "ti" => 'Nghệ An'),
   array( "id" => 42, "ti" => 'Ninh Bình'),
   array( "id" => 43, "ti" => 'Ninh Thuận'),
   array( "id" => 44, "ti" => 'Phú Thọ'),
   array( "id" => 45, "ti" => 'Phú Yên'),
   array( "id" => 46, "ti" => 'Quảng Ninh'),
   array( "id" => 47, "ti" => 'Quảng Nam'),
   array( "id" => 48, "ti" => 'Quảng Ngãi'),
   array( "id" => 49, "ti" => 'Quảng Trị'),
   array( "id" => 50, "ti" => 'Sóc Trăng'),
   array( "id" => 51, "ti" => 'Sơn La'),
   array( "id" => 52, "ti" => 'Tây Ninh'),
   array( "id" => 53, "ti" => 'Thái Bình'),
   array( "id" => 54, "ti" => 'Thái Nguyên'),
   array( "id" => 55, "ti" => 'Thanh Hóa'),
   array( "id" => 56, "ti" => 'Thừa Thiên Huế'),
   array( "id" => 57, "ti" => 'Tiền Giang'),
   array( "id" => 58, "ti" => 'Trà Vinh'),
   array( "id" => 59, "ti" => 'Tuyên Quang'),
   array( "id" => 60, "ti" => 'Vĩnh Long'),
   array( "id" => 61, "ti" => 'Vĩnh Phúc'),
   array( "id" => 62, "ti" => 'Yên Bái'),
);

