<?php

define('CONTROLLERS','/page/controllers/');

define('APIPOSTSTR', '/api/post/');
define('APIGETSTR', '/api/get/');
define('FOLDERDATAXML', 'media/information');
// define('FOLDERDATAXML', 'dataxml');
define('FOLDERUDATA', 'udata');

define('APIPOSTUSERSIGNUP', APIPOSTSTR.'signup');
define('APIPOSTUSERSIGNIN', APIPOSTSTR.'signin');
define('APIPOSTUSERSIGNINFB', APIPOSTSTR.'signinfb');
define('APIPOSTUSERSIGNOUT', APIPOSTSTR.'signout');
define('APIPOSTUSEREDIT', APIPOSTSTR.'userinfo');
define('APIPOSTUSERNAME', APIPOSTSTR.'username');
define('APIPOSTUSERSUB', APIPOSTSTR.'usersub');
define('APIPOSTUSERACTION', APIPOSTSTR.'useraction');
define('APIPOSTFORGOTPASSWORD', APIPOSTSTR.'forgotpassword');
define('APIPOSTCHANGEPASSWORD', APIPOSTSTR.'changepassword');
define('APIPOSTADMINSIGNIN', APIPOSTSTR.'adminsignin');
define('APIPOSTCONFIGPAGE', APIPOSTSTR.'config');
define('APIPOSTCONTACTUS',APIPOSTSTR.'contactus');
define('APIPOSTSAVEDATA',APIPOSTSTR.'savedata');
define('APIPOSTSEARCH',APIPOSTSTR.'search');
define('APIPOSTBLOG',APIPOSTSTR.'blog');
define('APIPOSTNEWS',APIPOSTSTR.'news');
define('APIPOSTJOB',APIPOSTSTR.'job');
define('APIPOSTCATEGORY',APIPOSTSTR.'category');
define('APIPOSTCATEGORYURL',APIPOSTSTR.'categoryurl');
define('APIPOSTSLIDE', APIPOSTSTR.'slide');
define('APIPOSTCOMPANY', APIPOSTSTR.'company');
define('APIPOSTUPLOADFILE', APIPOSTSTR.'uploadfile');
define('APIPOSTSENDMESSAGE', APIPOSTSTR.'sendmessage');
define('APIPOSTPAYMENT', APIPOSTSTR.'payment');
define('APIPOSTPROMO', APIPOSTSTR.'promo');
define('APIPOSTPROMOAPPLIED', APIPOSTSTR.'promoapplied');
define('APIPOSTADMINACTIVE', APIPOSTSTR.'admin_active');
define('APIPOSTURL', APIPOSTSTR.'url');
define('APIPOSTEMAIL', APIPOSTSTR.'email');
define('APIPOSTPAGEHTML', APIPOSTSTR.'pagehtml');
define('APIPOSTLANG', APIPOSTSTR.'language');
define('APIPOSTAPPLYSIGNUP', APIPOSTSTR.'applyandsignup');
define('APIPOSTSENDEMAILEDM', APIPOSTSTR.'send_email_edm');
define('APIPOSTMESSAGES', APIPOSTSTR.'messages');
define('APIPOSTCOMMENT', APIPOSTSTR.'comment');
define('APIPOSTFOLLOW', APIPOSTSTR.'follow');
define('APIPOSTADDDAYEMPLOYER', APIPOSTSTR.'add_day_to_user');


define('APIGETCONFIGPAGE', APIGETSTR.'config');
define('APIGETMENU', APIGETSTR.'menu');
define('APIGETMENUINFO', APIGETSTR.'menuinfo');
define('APIGETUSERINFO', APIGETSTR.'userinfo');
define('APIGETUSER', APIGETSTR.'user');
define('APIGETUSERMANAGER', APIGETSTR.'user_manager');
define('APIGETUSERMENU', APIGETSTR.'usermenu');
define('APIGETUSERSUB', APIGETSTR.'usersub');
define('APIGETUSERMENUINFO', APIGETSTR.'usermenuinfo');
define('APIGETUSERLISTID', APIGETSTR.'userlistid');
define('APIGETBLOG', APIGETSTR.'blog');
define('APIGETNEWS', APIGETSTR.'news');
define('APIGETJOB', APIGETSTR.'job');
define('APIGETEMAIL', APIGETSTR.'email');
define('APIGETJOBMAP', APIGETSTR.'jobmap');
define('APIGETCMP', APIGETSTR.'cmp');
define('APIGETPROMO', APIGETSTR.'promo');
define('APIGETPROMOAPPLIED', APIGETSTR.'promoapplied');
define('APIGETUSERACTION', APIGETSTR.'useraction');
define('APIGETJOBLISTID', APIGETSTR.'joblistid');
define('APIGETCATEGORY', APIGETSTR.'category');
define('APIGETSLIDE', APIGETSTR.'slide');
define('APIGETCOMPANY', APIGETSTR.'company');
define('APIGETLOCATION', APIGETSTR.'location');
define('APIGETUPLOADFILE', APIGETSTR.'uploadfile');
define('APIGETCHECKOUT', APIGETSTR.'checkout');
define('APIGETCONTACTUS', APIGETSTR.'contactus');
define('APIGETPAGEHTML', APIGETSTR.'pagehtml');
define('APIGETCVLISTID', APIGETSTR.'cvlistid');
define('APIGETCV', APIGETSTR.'cv');
define('APIGETCITY', APIGETSTR.'city');
define('APIGETDISTRICT', APIGETSTR.'district');
define('APIGETCMPLISTTXT', APIGETSTR.'cmplisttxt');
define('APIGETHISTORYSEARCH', APIGETSTR.'history_search');
define('APIGETJOBS', APIGETSTR.'jobs');
define('APIGETJOBSUGGEST', APIGETSTR.'jobsuggest');
define('APIGETMESSAGE', APIGETSTR.'messages');
define('APIGETJOBBRAND', APIGETSTR.'jobbrand');
define('APIGETCOMMENT', APIGETSTR.'comment');
define('APIGETFOLLOW', APIGETSTR.'follow');
define('APIGETADMINUPDATEDAYS', APIGETSTR.'admin_update_day_employer');

define('TABLE_CONTACTUS', 'contactus');
define('TABLE_SAVE_DATA', 'savedata');
define('TABLE_USER', 'user');
define('TABLE_USERSUB', 'usersub');
define('TABLE_URL', 'url');
define('TABLE_USER_SEARCH', 'user_search');
define('TABLE_USER_CV', 'user_cv');
define('TABLE_USER_NAME', 'user_name');
define('TABLE_USER_SAVED', 'user_saved');
define('TABLE_RECEIVE_EMAIL', 'receive_email');
define('TABLE_USER_ADDRESS', 'user_address');
define('TABLE_USER_PAYMENT', 'user_payment');
define('TABLE_USER_RECOVERYPW', 'user_recovery_pw');
define('TABLE_USER_MANAGER', 'user_manager');
define('TABLE_CATEGORY', 'category');
define('TABLE_JOB', 'jobs');
define('TABLE_JOB_CATEGORY', 'jobs_category');
define('TABLE_JOB_LOCATION', 'jobs_location');
define('TABLE_JOB_SAVED', 'jobs_saved');
define('TABLE_JOB_APPLIED', 'jobs_applied');
define('TABLE_NEWS', 'news');
define('TABLE_PAGEHTML', 'pagehtml');
define('TABLE_USER_WORK_HISTORY', 'user_work_history');
define('TABLE_USER_EDUCATION_HISTORY', 'user_education_history');
define('TABLE_MESSAGES', 'messages');
define('TABLE_COMMENT', 'user_comment');
define('TABLE_FOLLOW', 'user_follow');
define('TABLE_ADMIN_UPDATE_EMPLOYER_DAY', 'admin_update_day_employer');


define('TABLE_COMPANY', 'company');
define('TABLE_COMPANY_LOCATION', 'company_location');
define('TABLE_BLOG', 'blog');
define('TABLE_PROMO', 'promo');
define('TABLE_PROMO_APPLIED', 'promo_applied');

define('FOLDERHOME', FOLDERDATAXML.'/home/');
define('FOLDERMENU', FOLDERDATAXML.'/menu/');
define('FOLDERCATEGORY', FOLDERDATAXML.'/category/');
define('FOLDERBLOG', FOLDERDATAXML.'/blog/');
define('FOLDERJOB', FOLDERDATAXML.'/jobs/');
define('FOLDERUSER', FOLDERDATAXML.'/user/');
define('FOLDERCOMPANY', FOLDERDATAXML.'/company/');
define('FOLDERNEWS', FOLDERDATAXML.'/news/');

define('UDATAIMAGE','/media/images/');
define('UDATAMENU','/menu/');

define('FOLDERIMAGEMENU', 'media/images/images/menu/');
define('FOLDERIMAGECATEGORY', 'media/images/images/category/');
define('FOLDERIMAGEBLOG', 'media/images/images/blog/');
define('FOLDERIMAGECOMPANYFACEBOOK', 'media/images/images/company/facebook/');
define('FOLDERIMAGECOMPANY', 'media/images/images/company/');
define('FOLDERIMAGEUSER', 'media/images/images/user/');
define('FOLDERIMAGENEWS', 'media/images/images/news/');
define('FOLDERSLIDEMENU', 'media/images/slide/menu/');
define('FOLDERSLIDECATEGORY', 'media/images/slide/category/');
define('FOLDERSLIDEBLOG', 'media/images/slide/blog/');
define('FOLDERSLIDECOMPANY', 'media/images/slide/cmp/');
define('FOLDERSLIDEUSER', 'media/images/slide/user/');
define('FOLDERUPLOAD', 'media/images/upload/');